/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lacreacion.mg;

import com.lacreacion.mg.utils.CurrentUser;
import com.lacreacion.mg.utils.Varios;
import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import java.util.prefs.Preferences;
import javax.swing.DesktopManager;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.derby.drda.NetworkServerControl;

/**
 *
 * @author user
 */
public class MdiFrame extends javax.swing.JFrame {

    JDesktopPane desktop;
    DesktopManager manager;

    Map<String, String> persistenceMap = new HashMap<>();

    /**
     * Creates new form MDIFrame
     */
    public MdiFrame() {
        try {
            persistenceMap = Varios.getDatabaseIP();

            if (Boolean.parseBoolean(Preferences.userRoot().node("MG").get("isServer", "true"))) {
                NetworkServerControl server = new NetworkServerControl();
                server.start(null);
            }
            initComponents();

            desktop = new JDesktopPane();
            desktop.setBackground(Color.white);
            setContentPane(desktop);
            this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuLogin = new javax.swing.JMenuItem();
        mnuOp = new javax.swing.JMenu();
        mnuOpRemates = new javax.swing.JMenuItem();
        mnuOpPagos = new javax.swing.JMenuItem();
        mnuOpRemates1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuMiembros = new javax.swing.JMenuItem();
        mnuAdRemates = new javax.swing.JMenuItem();
        mnuAdCuotas = new javax.swing.JMenuItem();
        mnuAdCat = new javax.swing.JMenuItem();
        mnuAdTransf = new javax.swing.JMenuItem();
        mnuAdRecibos = new javax.swing.JMenuItem();
        mnuAdIglesia = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuAdConfig = new javax.swing.JMenuItem();
        mnuAdUsuarios = new javax.swing.JMenuItem();
        mnuAdRoles = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuAdInformes = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Usuario");

        mnuLogin.setText("Login");
        mnuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLoginActionPerformed(evt);
            }
        });
        jMenu1.add(mnuLogin);

        jMenuBar1.add(jMenu1);

        mnuOp.setText("Operaciones");

        mnuOpRemates.setText("Remates");
        mnuOpRemates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpRematesActionPerformed(evt);
            }
        });
        mnuOp.add(mnuOpRemates);

        mnuOpPagos.setText("Pagos");
        mnuOpPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpPagosActionPerformed(evt);
            }
        });
        mnuOp.add(mnuOpPagos);

        mnuOpRemates1.setText("Colectas");
        mnuOpRemates1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpRemates1ActionPerformed(evt);
            }
        });
        mnuOp.add(mnuOpRemates1);

        jMenuBar1.add(mnuOp);

        jMenu2.setText("Administracion");

        mnuMiembros.setText("Administrar Miembros");
        mnuMiembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMiembrosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuMiembros);

        mnuAdRemates.setText("Administrar Remates");
        mnuAdRemates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdRematesActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAdRemates);

        mnuAdCuotas.setText("Administrar Cuotas de Remates");
        mnuAdCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdCuotasActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAdCuotas);

        mnuAdCat.setText("Administrar Categorias de Articulos");
        mnuAdCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdCatActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAdCat);

        mnuAdTransf.setText("Administrar Transferencias");
        mnuAdTransf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdTransfActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAdTransf);

        mnuAdRecibos.setText("Administrar Recibos");
        mnuAdRecibos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdRecibosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAdRecibos);

        mnuAdIglesia.setText("Administrar Iglesia");
        mnuAdIglesia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdIglesiaActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAdIglesia);
        jMenu2.add(jSeparator1);

        mnuAdConfig.setText("Configuracion del Sistema");
        mnuAdConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdConfigActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAdConfig);

        mnuAdUsuarios.setText("Administrar Usuarios");
        mnuAdUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAdUsuarios);

        mnuAdRoles.setText("Administrar Grupos");
        mnuAdRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdRolesActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAdRoles);
        jMenu2.add(jSeparator2);

        mnuAdInformes.setText("Informes");
        mnuAdInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdInformesActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAdInformes);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 934, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuMiembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMiembrosActionPerformed
        try {
            FrameMiembros frame = new FrameMiembros();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }
    }//GEN-LAST:event_mnuMiembrosActionPerformed

    private void mnuAdCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdCatActionPerformed
        try {
            FrameRematesCategorias frame = new FrameRematesCategorias();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }

    }//GEN-LAST:event_mnuAdCatActionPerformed

    private void mnuOpRematesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpRematesActionPerformed
        try {
            FrameRematesDetalle frameR = new FrameRematesDetalle();
            frameR.setVisible(true);

            desktop.add(frameR);

            frameR.setSelected(true);
            frameR.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }
    }//GEN-LAST:event_mnuOpRematesActionPerformed

    private void mnuOpPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpPagosActionPerformed
        try {
            FramePagos frame = new FramePagos();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuOpPagosActionPerformed

    private void mnuAdConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdConfigActionPerformed
        try {
            FrameConfig frame = new FrameConfig();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }
    }//GEN-LAST:event_mnuAdConfigActionPerformed

    private void mnuAdTransfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdTransfActionPerformed
        try {
            FrameTransferencias frame = new FrameTransferencias();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mnuAdTransfActionPerformed

    private void mnuAdRecibosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdRecibosActionPerformed
        try {
            FrameRecibos frame = new FrameRecibos();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }
    }//GEN-LAST:event_mnuAdRecibosActionPerformed

    private void mnuAdRematesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdRematesActionPerformed
        try {
            FrameRematesAdmin frame = new FrameRematesAdmin();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }
    }//GEN-LAST:event_mnuAdRematesActionPerformed

    private void mnuAdCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdCuotasActionPerformed
        try {
            FrameCuotasAdmin frame = new FrameCuotasAdmin();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }
    }//GEN-LAST:event_mnuAdCuotasActionPerformed

    private void mnuAdIglesiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdIglesiaActionPerformed
        try {
            FrameIglesiaAdmin frame = new FrameIglesiaAdmin();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
        }
    }//GEN-LAST:event_mnuAdIglesiaActionPerformed

    private void mnuAdInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdInformesActionPerformed
        try {
            FrameInformes frame = new FrameInformes();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mnuAdInformesActionPerformed

    private void mnuOpRemates1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpRemates1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuOpRemates1ActionPerformed

    private void mnuAdUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdUsuariosActionPerformed
        try {
            FrameUsuariosAdmin frame = new FrameUsuariosAdmin();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mnuAdUsuariosActionPerformed

    private void mnuAdRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdRolesActionPerformed
        try {
            FrameRolesAdmin frame = new FrameRolesAdmin();
            frame.setVisible(true);

            desktop.add(frame);

            frame.setSelected(true);
            frame.setMaximum(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mnuAdRolesActionPerformed

    private void mnuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLoginActionPerformed
        try {
            FormLogin frame = new FormLogin(this, true);
            frame.setVisible(true);
            CurrentUser currentUser = CurrentUser.getInstance();
            JOptionPane.showMessageDialog(null, currentUser.getUser().getNombre());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, Thread.currentThread().getStackTrace()[1].getMethodName() + " - " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mnuLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
             System.out.println(info.getName());
             if ("Nimbus".equals(info.getName())) {
             javax.swing.UIManager.setLookAndFeel(info.getClassName());
             break;
             }*/
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MdiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MdiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MdiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MdiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MdiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mnuAdCat;
    private javax.swing.JMenuItem mnuAdConfig;
    private javax.swing.JMenuItem mnuAdCuotas;
    private javax.swing.JMenuItem mnuAdIglesia;
    private javax.swing.JMenuItem mnuAdInformes;
    private javax.swing.JMenuItem mnuAdRecibos;
    private javax.swing.JMenuItem mnuAdRemates;
    private javax.swing.JMenuItem mnuAdRoles;
    private javax.swing.JMenuItem mnuAdTransf;
    private javax.swing.JMenuItem mnuAdUsuarios;
    private javax.swing.JMenuItem mnuLogin;
    private javax.swing.JMenuItem mnuMiembros;
    private javax.swing.JMenu mnuOp;
    private javax.swing.JMenuItem mnuOpPagos;
    private javax.swing.JMenuItem mnuOpRemates;
    private javax.swing.JMenuItem mnuOpRemates1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the databaseIP
     */
}
