INSERT INTO MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO (DESCRIPCION) VALUES ('Aporte por Debito Manual');
INSERT INTO MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO (DESCRIPCION) VALUES ('Personas con Discapacidad');

CREATE TABLE MG.TBL_DONACIONES_VARIAS_DETALLE (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	FECHAHORA TIMESTAMP NOT NULL,
	OBSERVACION VARCHAR(255),
	MONTO INTEGER NOT NULL,
	ID_ENTIDAD INTEGER NOT NULL,
	ID_CENTRO_DE_COSTO INTEGER NOT NULL,
        ID_FORMA_DE_PAGO_PREFERIDA INTEGER NOT NULL DEFAULT 1,
	ID_USER INTEGER,
	PRIMARY KEY (ID)
);

ALTER TABLE MG.TBL_DONACIONES_VARIAS_DETALLE
	ADD FOREIGN KEY (ID_CENTRO_DE_COSTO)
	REFERENCES MG.TBL_CENTROS_DE_COSTO (ID) ON DELETE RESTRICT;

ALTER TABLE MG.TBL_DONACIONES_VARIAS_DETALLE
	ADD FOREIGN KEY (ID_ENTIDAD)
	REFERENCES MG.TBL_ENTIDADES (ID) ON DELETE RESTRICT;

ALTER TABLE MG.TBL_DONACIONES_VARIAS_DETALLE
	ADD FOREIGN KEY (ID_FORMA_DE_PAGO_PREFERIDA)
	REFERENCES MG.TBL_FORMAS_DE_PAGO (ID) ON DELETE RESTRICT;

ALTER TABLE MG.TBL_DONACIONES_VARIAS_DETALLE
	ADD FOREIGN KEY (ID_USER)
	REFERENCES MG.TBL_USERS (ID) ON DELETE RESTRICT;

CREATE TABLE MG.TBL_DONACIONES_VARIAS_DETALLE_ASIENTOS (
    ID_DONACIONES_VARIAS_DETALLE INTEGER NOT NULL,
    ID_ASIENTO INTEGER NOT NULL
);

ALTER TABLE MG.TBL_DONACIONES_VARIAS_DETALLE_ASIENTOS
	ADD FOREIGN KEY (ID_DONACIONES_VARIAS_DETALLE) REFERENCES MG.TBL_DONACIONES_VARIAS_DETALLE (ID);

ALTER TABLE MG.TBL_DONACIONES_VARIAS_DETALLE_ASIENTOS
	ADD FOREIGN KEY (ID_ASIENTO) REFERENCES MG.TBL_ASIENTOS (ID);