CREATE TABLE MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS (
        ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
        ID_ENTIDAD INTEGER NOT NULL,
        ANO_MES INTEGER NOT NULL,
        ID_CATEGORIA_DE_PAGO INTEGER NOT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS
	ADD FOREIGN KEY (ID_ENTIDAD) REFERENCES MG.TBL_ENTIDADES (ID);

ALTER TABLE MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS
	ADD FOREIGN KEY (ID_CATEGORIA_DE_PAGO) REFERENCES MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO (ID);

INSERT INTO MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS
	(ID_ENTIDAD, ANO_MES, ID_CATEGORIA_DE_PAGO)
        SELECT ID AS ID_ENTIDAD, 201601 AS ANO_MES, ID_MIEMBROS_CATEGORIA_DE_PAGO AS ID_CATEGORIA_DE_PAGO FROM TBL_ENTIDADES
        WHERE ID_MIEMBROS_CATEGORIA_DE_PAGO IS NOT NULL;

CREATE TABLE MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR (
        ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
        ID_ENTIDAD INTEGER NOT NULL,
        ANO INTEGER NOT NULL,
        IMPORTE_MESNUAL BIGINT NOT NULL,
        SALDO_ANTERIOR BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR
	ADD FOREIGN KEY (ID_ENTIDAD) REFERENCES MG.TBL_ENTIDADES (ID);

INSERT INTO MG.TBL_APORTES_IMPORTE_MENSUAL_SALDO_ANTERIOR
	(ID_ENTIDAD, ANO, IMPORTE_MESNUAL, SALDO_ANTERIOR)
        SELECT ID AS ID_ENTIDAD, 2017 AS ANO, APORTE_MENSUAL AS IMPORTE_MENSUAL, APORTE_SALDO_ANTERIOR AS SALDO_ANTERIOR FROM TBL_ENTIDADES
        WHERE APORTE_SALDO_ANTERIOR IS NOT NULL;

ALTER TABLE MG.TBL_ENTIDADES ADD COLUMN CANTIDAD_DE_DEPENDIENTES_APORTANTES INTEGER NOT NULL DEFAULT 1;