DROP TABLE MG.TBL_FACTURAS_TRANSACCIONES;
DROP TABLE MG.TBL_FACTURAS_COMPRAS;
DROP TABLE MG.TBL_TRANSACCIONES;
DROP TABLE MG.TBL_CENTROS_DE_COSTO;
DROP TABLE MG.TBL_CUENTAS_CONTABLES;
DROP TABLE MG.TBL_RUBROS_DDJJ;


CREATE TABLE MG.TBL_FACTURAS_COMPRAS (
        ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
        NRO INTEGER NOT NULL,
        NRO_TIMBRADO INTEGER NOT NULL,
        VENCIMIENTO_TIMBRADO TIMESTAMP NOT NULL,
        FECHAHORA TIMESTAMP NOT NULL,
        RAZON_SOCIAL VARCHAR(50) NOT NULL,
        RUC VARCHAR(20) NOT NULL,
        IMPORTE INTEGER NOT NULL,
        ANULADO BOOLEAN DEFAULT FALSE NOT NULL,
        ID_USER INTEGER NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_CUENTAS_CONTABLES (
    ID INTEGER NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    ID_CUENTA_MADRE INTEGER,
    RUBRO_DDJJ INTEGER,
    ES_CUENTA_MADRE BOOLEAN,
    PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_RUBROS_DDJJ (
    ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_CENTROS_DE_COSTO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_TRANSACCIONES (
    ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    FECHAHORA TIMESTAMP NOT NULL,
    TIPO_TRANSACCION INTEGER NOT NULL,
    ID_CENTRO_DE_COSTO INTEGER NOT NULL,
    ID_CUENTA_CONTABLE INTEGER NOT NULL,
    ID_USER INTEGER NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_FACTURAS_TRANSACCIONES (
    ID_FACTURA INTEGER NOT NULL,
    ID_TRANSACCION INTEGER NOT NULL
);

ALTER TABLE MG.TBL_FACTURAS_TRANSACCIONES
	ADD FOREIGN KEY (ID_FACTURA)
	REFERENCES MG.TBL_FACTURAS_COMPRAS (ID);

ALTER TABLE MG.TBL_FACTURAS_TRANSACCIONES
	ADD FOREIGN KEY (ID_TRANSACCION)
	REFERENCES MG.TBL_TRANSACCIONES (ID);

ALTER TABLE MG.TBL_TRANSACCIONES
	ADD FOREIGN KEY (ID_CENTRO_DE_COSTO)
	REFERENCES MG.TBL_CENTROS_DE_COSTO (ID);

ALTER TABLE MG.TBL_TRANSACCIONES
	ADD FOREIGN KEY (ID_CUENTA_CONTABLE)
	REFERENCES MG.TBL_CUENTAS_CONTABLES (ID);

ALTER TABLE MG.TBL_TRANSACCIONES
	ADD FOREIGN KEY (ID_USER)
	REFERENCES MG.TBL_USERS (ID);

ALTER TABLE MG.TBL_CUENTAS_CONTABLES
	ADD FOREIGN KEY (RUBRO_DDJJ)
	REFERENCES MG.TBL_RUBROS_DDJJ (ID);

ALTER TABLE MG.TBL_CUENTAS_CONTABLES
	ADD FOREIGN KEY (ID_CUENTA_MADRE)
	REFERENCES MG.TBL_CUENTAS_CONTABLES (ID);