ALTER TABLE MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS
	ADD COLUMN FECHA TIMESTAMP;
ALTER TABLE MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS
	ADD COLUMN OBSERVACIONES VARCHAR(255);
UPDATE MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS
SET FECHA = CAST(SUBSTR(CAST(ANO_MES AS CHAR(6)),1,4) || '-' || SUBSTR(CAST(ANO_MES AS CHAR(6)),5,2) || '-01 00:00:00' AS TIMESTAMP);
ALTER TABLE MG.TBL_ENTIDADES_HISTORICO_CATEGORIAS
	DROP COLUMN ANO_MES;