DROP TABLE MG.TBL_FACTURAS_COMPRA_ASIENTOS;
DROP TABLE MG.TBL_FACTURAS_COMPRA;
DROP TABLE MG.TBL_AUTOFACTURAS;
DROP TABLE MG.TBL_TIMBRADOS_AUTOFACTURAS;
DROP TABLE MG.TBL_ASIENTOS;
DROP TABLE MG.TBL_CENTROS_DE_COSTO;
DROP TABLE MG.TBL_CUENTAS_CONTABLES;

CREATE TABLE MG.TBL_FACTURAS_COMPRA (
        ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
        NRO INTEGER NOT NULL,
        NRO_TIMBRADO INTEGER NOT NULL,
        VENCIMIENTO_TIMBRADO TIMESTAMP NOT NULL,
        CONDICION_CONTADO BOOLEAN DEFAULT TRUE NOT NULL,
        FECHAHORA TIMESTAMP NOT NULL,
        RAZON_SOCIAL VARCHAR(50) NOT NULL,
        RUC VARCHAR(20) NOT NULL,
        MONTO_EXENTAS INTEGER NOT NULL,
        MONTO_IVA5 INTEGER NOT NULL,
        MONTO_IVA10 INTEGER NOT NULL,
        IVA5 INTEGER NOT NULL,
        IVA10 INTEGER NOT NULL,
        ANULADO BOOLEAN DEFAULT FALSE NOT NULL,
        ID_USER INTEGER NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_AUTOFACTURAS (
        ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
        NRO INTEGER NOT NULL,
        NRO_TIMBRADO INTEGER NOT NULL,
        CONDICION_CONTADO BOOLEAN DEFAULT TRUE NOT NULL,
        FECHAHORA TIMESTAMP NOT NULL,
        RAZON_SOCIAL VARCHAR(50) NOT NULL,
        RUC VARCHAR(20) NOT NULL,
        MONTO_EXENTAS INTEGER NOT NULL,
        MONTO_IVA5 INTEGER NOT NULL,
        MONTO_IVA10 INTEGER NOT NULL,
        IVA5 INTEGER NOT NULL,
        IVA10 INTEGER NOT NULL,
        ANULADO BOOLEAN DEFAULT FALSE NOT NULL,
        ID_USER INTEGER NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_CUENTAS_CONTABLES (
    ID INTEGER NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    ID_CUENTA_MADRE INTEGER,
    IMPUTABLE BOOLEAN,
    PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_CENTROS_DE_COSTO (
    ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_ASIENTOS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    FECHAHORA TIMESTAMP NOT NULL,
    TIPO_ASIENTO INTEGER NOT NULL,
    ID_CENTRO_DE_COSTO INTEGER NOT NULL,
    ID_CUENTA_CONTABLE INTEGER NOT NULL,
    MONTO INTEGER NOT NULL,
    ID_USER INTEGER NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_FACTURAS_COMPRA_ASIENTOS (
    ID_FACTURA_COMPRA INTEGER NOT NULL,
    ID_ASIENTO INTEGER NOT NULL
);

CREATE TABLE MG.TBL_TIMBRADOS_AUTOFACTURAS (
        NRO INTEGER NOT NULL,
        FECHA_INICIO TIMESTAMP NOT NULL,
        FECHA_VENCIMIENTO TIMESTAMP NOT NULL,
        NRO_FACTURA_INCIO INTEGER NOT NULL,
        NRO_FACTURA_FIN INTEGER NOT NULL,
        ACTIVO BOOLEAN NOT NULL,
        ID_USER INTEGER NOT NULL,
	PRIMARY KEY (NRO)
);

ALTER TABLE MG.TBL_FACTURAS_COMPRA_ASIENTOS
	ADD FOREIGN KEY (ID_FACTURA_COMPRA)
	REFERENCES MG.TBL_FACTURAS_COMPRA (ID);

ALTER TABLE MG.TBL_FACTURAS_COMPRA_ASIENTOS
	ADD FOREIGN KEY (ID_ASIENTO)
	REFERENCES MG.TBL_ASIENTOS (ID);

ALTER TABLE MG.TBL_ASIENTOS
	ADD FOREIGN KEY (ID_CENTRO_DE_COSTO)
	REFERENCES MG.TBL_CENTROS_DE_COSTO (ID);

ALTER TABLE MG.TBL_ASIENTOS
	ADD FOREIGN KEY (ID_CUENTA_CONTABLE)
	REFERENCES MG.TBL_CUENTAS_CONTABLES (ID);

ALTER TABLE MG.TBL_ASIENTOS
	ADD FOREIGN KEY (ID_USER)
	REFERENCES MG.TBL_USERS (ID);

ALTER TABLE MG.TBL_CUENTAS_CONTABLES
	ADD FOREIGN KEY (ID_CUENTA_MADRE)
	REFERENCES MG.TBL_CUENTAS_CONTABLES (ID);

ALTER TABLE MG.TBL_FACTURAS_COMPRA
	ADD FOREIGN KEY (ID_USER)
	REFERENCES MG.TBL_USERS (ID);

ALTER TABLE MG.TBL_AUTOFACTURAS
	ADD FOREIGN KEY (ID_USER)
	REFERENCES MG.TBL_USERS (ID);

ALTER TABLE MG.TBL_AUTOFACTURAS
	ADD FOREIGN KEY (NRO_TIMBRADO)
	REFERENCES MG.TBL_TIMBRADOS_AUTOFACTURAS (NRO);

ALTER TABLE MG.TBL_ASIENTOS
	ADD FOREIGN KEY (ID_USER)
	REFERENCES MG.TBL_USERS (ID);

INSERT INTO MG.TBL_CUENTAS_CONTABLES (ID, DESCRIPCION, ID_CUENTA_MADRE, IMPUTABLE) VALUES (100000000, 'ACTIVO',NULL,FALSE);
INSERT INTO MG.TBL_CUENTAS_CONTABLES (ID, DESCRIPCION, ID_CUENTA_MADRE, IMPUTABLE) VALUES (200000000, 'PASIVO',NULL,FALSE);
INSERT INTO MG.TBL_CUENTAS_CONTABLES (ID, DESCRIPCION, ID_CUENTA_MADRE, IMPUTABLE) VALUES (300000000, 'PATRIMONIO NETO',NULL,FALSE);
INSERT INTO MG.TBL_CUENTAS_CONTABLES (ID, DESCRIPCION, ID_CUENTA_MADRE, IMPUTABLE) VALUES (400000000, 'INGRESOS',NULL,FALSE);
INSERT INTO MG.TBL_CUENTAS_CONTABLES (ID, DESCRIPCION, ID_CUENTA_MADRE, IMPUTABLE) VALUES (500000000, 'EGRESOS',NULL,FALSE);