SELECT SUM(c.MONTO), SUM(c.atemp) FROM
(SELECT a.ID, a.MONTO, SUM(att.MONTO) as atemp FROM
MG.TBL_ASIENTOS a, MG.TBL_ASIENTOS_ASIENTOS_TEMPORALES aat, MG.TBL_ASIENTOS_TEMPORALES att
where aat.ID_ASIENTO = a.ID AND aat.ID_ASIENTO_TEMPORAL = att.ID
group by a.ID, a.MONTO) c
where c.MONTO <> c.atemp

SELECT f.NRO, f.RAZON_SOCIAL, f.IMPORTE_DONACION+f.IMPORTE_APORTE, SUM(c.atemp)
FROM
MG.TBL_FACTURAS f,
MG.TBL_FACTURAS_ASIENTOS fa,
(SELECT a.ID, a.MONTO as asientos, att.MONTO as atemp FROM
MG.TBL_ASIENTOS a, MG.TBL_ASIENTOS_ASIENTOS_TEMPORALES aat, MG.TBL_ASIENTOS_TEMPORALES att
where aat.ID_ASIENTO = a.ID AND aat.ID_ASIENTO_TEMPORAL = att.ID
AND a.MONTO <> att.MONTO) c
WHERE f.NRO = fa.NRO_FACTURA
AND c.ID = fa.ID_ASIENTO
AND f.ANULADO = false
GROUP BY f.NRO, f.RAZON_SOCIAL, f.IMPORTE_DONACION+f.IMPORTE_APORTE

/*SELECT POR TRANSFERENCIA*/
SELECT t.ID, att.MONTO, t.MONTO_APORTE+t.MONTO_DONACION as transf
FROM MG.TBL_TRANSFERENCIAS t, MG.TBL_TRANSFERENCIAS_ASIENTOS_TEMPORALES tat, MG.TBL_ASIENTOS_TEMPORALES att
WHERE tat.ID_TRANSFERENCIA = t.ID AND tat.ID_ASIENTO_TEMPORAL = att.ID
AND t.ID = 6620