DROP TABLE MG.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA;
DROP TABLE MG.TBL_RECIBOS_COMPRA_ASIENTOS;
DROP TABLE MG.TBL_RECIBOS_COMPRA;

CREATE TABLE MG.TBL_RECIBOS_COMPRA (
        ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
        NRO VARCHAR(30) NOT NULL,
        FECHAHORA TIMESTAMP NOT NULL,
        RAZON_SOCIAL VARCHAR(255) NOT NULL,
        RUC VARCHAR(20) NOT NULL,
        MONTO INTEGER DEFAULT 0 NOT NULL,
        OBSERVACION VARCHAR(255),
        ID_USER INTEGER NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA (
    ID_RECIBO INTEGER NOT NULL,
    ID_FACTURA_COMPRA INTEGER NOT NULL,
    MONTO INTEGER DEFAULT 0 NOT NULL,
    PRIMARY KEY (ID_RECIBO, ID_FACTURA_COMPRA)
);

CREATE TABLE MG.TBL_RECIBOS_COMPRA_ASIENTOS (
    ID_RECIBO INTEGER NOT NULL,
    ID_ASIENTO INTEGER NOT NULL
);

ALTER TABLE MG.TBL_RECIBOS_COMPRA
	ADD FOREIGN KEY (ID_USER) REFERENCES MG.TBL_USERS (ID);

ALTER TABLE MG.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA
	ADD FOREIGN KEY (ID_RECIBO) REFERENCES MG.TBL_RECIBOS_COMPRA (ID);
ALTER TABLE MG.TBL_RECIBOS_COMPRA_FACTURAS_COMPRA
	ADD FOREIGN KEY (ID_FACTURA_COMPRA) REFERENCES MG.TBL_FACTURAS_COMPRA (ID);

ALTER TABLE MG.TBL_RECIBOS_COMPRA_ASIENTOS
	ADD FOREIGN KEY (ID_RECIBO) REFERENCES MG.TBL_RECIBOS_COMPRA (ID);
ALTER TABLE MG.TBL_RECIBOS_COMPRA_ASIENTOS
	ADD FOREIGN KEY (ID_ASIENTO) REFERENCES MG.TBL_ASIENTOS (ID);

ALTER TABLE MG.TBL_NOTAS_DE_CREDITO_COMPRAS
	ADD FOREIGN KEY (ID_USER) REFERENCES MG.TBL_USERS (ID);