DROP TABLE MG.TBL_DONACIONES_VARIAS_DETALLE_ASIENTOS;
DROP TABLE MG.TBL_DONACIONES_VARIAS_DETALLE;

INSERT INTO MG.TBL_EVENTO_TIPOS (ID, DESCRIPCION) VALUES (4, 'Aportes y Donaciones Varias');

ALTER TABLE MG.TBL_AUTOFACTURAS
	ADD COLUMN CONDICION_CONTADO BOOLEAN NOT NULL DEFAULT TRUE;