ALTER TABLE MG.TBL_EVENTOS
	ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_EVENTO_DETALLE
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_CATEGORIAS_ARTICULOS
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_GRUPOS
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_MIEMBROS_RELACIONES
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_MIEMBROS_RELACIONES_TIPOS
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_MIEMBROS_RELACIONES_ROLES
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_MIEMBROS_FAMILIAS
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_ENTIDADES
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_AREAS_SERVICIO_EN_IGLESIA
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_RECIBOS
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_ROLES
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_TRANSFERENCIAS
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_USERS
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_FACTURAS_COMPRA
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_AUTOFACTURAS
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_NOTAS_DE_CREDITO
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_CENTROS_DE_COSTO
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_ASIENTOS
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_ASIENTOS_TEMPORALES
        ALTER COLUMN ID SET INCREMENT BY 1;

ALTER TABLE MG.TBL_TIMBRADOS_AUTOFACTURAS
        ALTER COLUMN ID SET INCREMENT BY 1;