ALTER TABLE TBL_ENTIDADES
    ADD COLUMN APORTE_SALDO_ANTERIOR BIGINT DEFAULT 0;

UPDATE MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO SET DESCRIPCION = 'Exonerado - Estudiante' WHERE ID = 1;
UPDATE MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO SET DESCRIPCION = 'Exonerado - Miembro Nuevo' WHERE ID = 2;
UPDATE MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO SET DESCRIPCION = 'Aporta - Con Debito Automatico' WHERE ID = 3;
UPDATE MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO SET DESCRIPCION = 'Exonerado - Tercera Edad' WHERE ID = 4;
UPDATE MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO SET DESCRIPCION = 'Exonerado - Viudo/a' WHERE ID = 5;
UPDATE MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO SET DESCRIPCION = 'Aporta - Sin Debito Automatico' WHERE ID = 6;
UPDATE MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO SET DESCRIPCION = 'Exonerado - Discapacidad' WHERE ID = 7;
UPDATE MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO SET DESCRIPCION = 'Exonerado - Insolvencia' WHERE ID = 8;

ALTER TABLE TBL_ASIENTOS
    ADD COLUMN ASIENTO_MANUAL BOOLEAN;