ALTER TABLE TBL_ENTIDADES
    ADD COLUMN MES_INICIO_APORTE INTEGER DEFAULT 2;
ALTER TABLE TBL_ENTIDADES
    ADD COLUMN MES_FIN_APORTE INTEGER DEFAULT 11;

ALTER TABLE TBL_MIEMBROS_CATEGORIAS_DE_PAGO
    ADD COLUMN ES_ACTIVACION BOOLEAN;

UPDATE MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO SET ES_ACTIVACION = FALSE WHERE ID = 1;
UPDATE MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO SET ES_ACTIVACION = FALSE WHERE ID = 2;
UPDATE MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO SET ES_ACTIVACION = TRUE WHERE ID = 3;
UPDATE MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO SET ES_ACTIVACION = FALSE WHERE ID = 4;
UPDATE MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO SET ES_ACTIVACION = FALSE WHERE ID = 5;
UPDATE MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO SET ES_ACTIVACION = TRUE WHERE ID = 6;
UPDATE MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO SET ES_ACTIVACION = FALSE WHERE ID = 7;
UPDATE MG.TBL_MIEMBROS_CATEGORIAS_DE_PAGO SET ES_ACTIVACION = FALSE WHERE ID = 8;