DROP TABLE MG.TBL_FACTURAS_COMPRAS;

CREATE TABLE MG.TBL_FACTURAS_COMPRAS (
        ID INTEGER NOT NULL,
        NRO INTEGER NOT NULL,
        ID_TIMBRADO INTEGER NOT NULL,
        FECHAHORA TIMESTAMP NOT NULL,
        RAZON_SOCIAL VARCHAR(50) NOT NULL,
        RUC VARCHAR(20) NOT NULL,
        IMPORTE INTEGER NOT NULL,
        ANULADO BOOLEAN DEFAULT FALSE NOT NULL,
        ID_USER INTEGER NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_CUENTAS_CONTABLES (
    ID INTEGER NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    ID_CUENTA_MADRE INTEGER,
);

CREATE TABLE MG.TBL_CENTROS_DE_COSTO (
    ID INTEGER NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_TRANSACCIONES (
    ID INTEGER NOT NULL,
    ID_FACTURA INTEGER NOT NULL,
    FECHAHORA TIMESTAMP NOT NULL,
    TIPO_TRANSACCION INTEGER NOT NULL,
    ID_CENTRO_DE_COSTO INTEGER NOT NULL,
    ID_CUENTA_CONTABLE INTEGER NOT NULL,
    ID_USER INTEGER NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE MG.TBL_TRANSACCIONES
	ADD FOREIGN KEY (ID_FACTURA)
	REFERENCES MG.TBL_FACTURAS_COMPRAS (ID);

ALTER TABLE MG.TBL_TRANSACCIONES
	ADD FOREIGN KEY (ID_CENTRO_DE_COSTO)
	REFERENCES MG.TBL_CENTROS_DE_COSTO (ID);

ALTER TABLE MG.TBL_TRANSACCIONES
	ADD FOREIGN KEY (ID_CENTRO_DE_COSTO)
	REFERENCES MG.TBL_CENTROS_DE_COSTO (ID);

ALTER TABLE MG.TBL_TRANSACCIONES
	ADD FOREIGN KEY (ID_CUENTA_CONTABLE)
	REFERENCES MG.TBL_CUENTAS_CONTABLES (ID);

ALTER TABLE MG.TBL_TRANSACCIONES
	ADD FOREIGN KEY (ID_USER)
	REFERENCES MG.TBL_USERS (ID);
