RENAME TABLE MG.TBL_NOTAS_DE_CREDITO TO TBL_NOTAS_DE_CREDITO_COMPRAS;
RENAME TABLE MG.TBL_NOTAS_DE_CREDITO_ASIENTOS TO TBL_NOTAS_DE_CREDITO_COMPRAS_ASIENTOS;

CREATE TABLE MG.TBL_TIMBRADOS_NOTAS_DE_CREDITO (
        ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
        NRO VARCHAR(8) NOT NULL,
        ESTABLECIMIENTO VARCHAR(3) NOT NULL,
        PUNTO_DE_EXPEDICION VARCHAR(3) NOT NULL,
        FECHA_INICIO TIMESTAMP NOT NULL,
        FECHA_VENCIMIENTO TIMESTAMP NOT NULL,
        NRO_NOTA_DE_CREDITO_INCIO INTEGER NOT NULL,
        NRO_NOTA_DE_CREDITO_FIN INTEGER NOT NULL,
        ACTIVO BOOLEAN NOT NULL,
        ID_USER INTEGER NOT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE MG.TBL_TIMBRADOS_NOTAS_DE_CREDITO
	ADD FOREIGN KEY (ID_USER) REFERENCES MG.TBL_USERS (ID);

CREATE TABLE MG.TBL_NOTAS_DE_CREDITO (
        ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
        NRO VARCHAR(15) NOT NULL,
        ID_TIMBRADO INTEGER NOT NULL,
        FECHAHORA TIMESTAMP NOT NULL,
        NRO_FACTURA INTEGER NOT NULL,
        ANULADO BOOLEAN DEFAULT FALSE NOT NULL,
        ID_USER INTEGER NOT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE MG.TBL_NOTAS_DE_CREDITO
	ADD FOREIGN KEY (ID_TIMBRADO) REFERENCES MG.TBL_TIMBRADOS_NOTAS_DE_CREDITO (ID);

ALTER TABLE MG.TBL_NOTAS_DE_CREDITO
	ADD FOREIGN KEY (NRO_FACTURA) REFERENCES MG.TBL_FACTURAS (NRO);

ALTER TABLE MG.TBL_NOTAS_DE_CREDITO
	ADD FOREIGN KEY (ID_USER) REFERENCES MG.TBL_USERS (ID);

CREATE TABLE MG.TBL_NOTAS_DE_CREDITO_ASIENTOS (
    ID_NOTA_DE_CREDITO INTEGER NOT NULL,
    ID_ASIENTO INTEGER NOT NULL
);

ALTER TABLE MG.TBL_NOTAS_DE_CREDITO_ASIENTOS
	ADD FOREIGN KEY (ID_NOTA_DE_CREDITO) REFERENCES MG.TBL_NOTAS_DE_CREDITO (ID);

ALTER TABLE MG.TBL_NOTAS_DE_CREDITO_ASIENTOS
	ADD FOREIGN KEY (ID_ASIENTO) REFERENCES MG.TBL_ASIENTOS (ID);