ALTER TABLE MG.TBL_TRANSFERENCIAS
	ADD COLUMN ID_EVENTO INTEGER;

ALTER TABLE MG.TBL_TRANSFERENCIAS
	ADD FOREIGN KEY (ID_EVENTO) REFERENCES MG.TBL_EVENTOS (ID);

ALTER TABLE MG.TBL_RECIBOS
	ADD COLUMN ID_EVENTO INTEGER;

ALTER TABLE MG.TBL_RECIBOS
	ADD FOREIGN KEY (ID_EVENTO) REFERENCES MG.TBL_EVENTOS (ID);

ALTER TABLE MG.TBL_EVENTOS
        ADD COLUMN ID_CENTRO_DE_COSTO INTEGER;

ALTER TABLE MG.TBL_FACTURAS
	ADD COLUMN DOMICILIO VARCHAR(255);

ALTER TABLE MG.TBL_FACTURAS
	ADD COLUMN CASILLA_DE_CORREO INTEGER;