ALTER TABLE TBL_ASIENTOS
    ADD COLUMN  ID_CENTRO_DE_COSTO_DEBE INTEGER NOT NULL DEFAULT 0;

ALTER TABLE TBL_ASIENTOS
    ADD COLUMN  ID_CENTRO_DE_COSTO_HABER INTEGER NOT NULL DEFAULT 0;

UPDATE TBL_ASIENTOS
    SET ID_CENTRO_DE_COSTO_DEBE = ID_CENTRO_DE_COSTO;

UPDATE TBL_ASIENTOS
    SET ID_CENTRO_DE_COSTO_HABER = ID_CENTRO_DE_COSTO;

ALTER TABLE MG.TBL_ASIENTOS
	ADD FOREIGN KEY (ID_CENTRO_DE_COSTO_DEBE) REFERENCES MG.TBL_CENTROS_DE_COSTO (ID);

ALTER TABLE MG.TBL_ASIENTOS
	ADD FOREIGN KEY (ID_CENTRO_DE_COSTO_HABER) REFERENCES MG.TBL_CENTROS_DE_COSTO (ID);

ALTER TABLE MG.TBL_ASIENTOS
     DROP COLUMN ID_CENTRO_DE_COSTO;



ALTER TABLE TBL_ASIENTOS_TEMPORALES
    ADD COLUMN  ID_CENTRO_DE_COSTO_DEBE INTEGER NOT NULL DEFAULT 0;

ALTER TABLE TBL_ASIENTOS_TEMPORALES
    ADD COLUMN  ID_CENTRO_DE_COSTO_HABER INTEGER NOT NULL DEFAULT 0;

UPDATE TBL_ASIENTOS_TEMPORALES
    SET ID_CENTRO_DE_COSTO_DEBE = ID_CENTRO_DE_COSTO;

UPDATE TBL_ASIENTOS_TEMPORALES
    SET ID_CENTRO_DE_COSTO_HABER = ID_CENTRO_DE_COSTO;

ALTER TABLE MG.TBL_ASIENTOS_TEMPORALES
	ADD FOREIGN KEY (ID_CENTRO_DE_COSTO_DEBE) REFERENCES MG.TBL_CENTROS_DE_COSTO (ID);

ALTER TABLE MG.TBL_ASIENTOS_TEMPORALES
	ADD FOREIGN KEY (ID_CENTRO_DE_COSTO_HABER) REFERENCES MG.TBL_CENTROS_DE_COSTO (ID);

ALTER TABLE MG.TBL_ASIENTOS_TEMPORALES
     DROP COLUMN ID_CENTRO_DE_COSTO;