DROP TABLE MG.TBL_RECIBOS;
DROP TABLE MG.TBL_TRANSFERENCIAS;

CREATE TABLE MG.TBL_RECIBOS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    FECHAHORA TIMESTAMP NOT NULL,
    CONCEPTO VARCHAR(50),
    MONTO INTEGER NOT NULL,
    PORCENTAJE_APORTE INTEGER NOT NULL,
    ID_ENTIDAD INTEGER NOT NULL,
    ID_EVENTO_TIPO INTEGER NOT NULL,
    ID_USER INTEGER NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_TRANSFERENCIAS (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	FECHAHORA TIMESTAMP NOT NULL,
	CONCEPTO VARCHAR(50),
	MONTO INTEGER NOT NULL,
	PORCENTAJE_APORTE INTEGER NOT NULL,
	ID_ENTIDAD INTEGER NOT NULL,
        ID_EVENTO_TIPO INTEGER NOT NULL,
        COBRADO BOOLEAN NOT NULL DEFAULT FALSE,
	ID_USER INTEGER NOT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE MG.TBL_RECIBOS
	ADD FOREIGN KEY (ID_ENTIDAD)
	REFERENCES MG.TBL_ENTIDADES (ID);

ALTER TABLE MG.TBL_RECIBOS
	ADD FOREIGN KEY (ID_EVENTO_TIPO)
	REFERENCES MG.TBL_EVENTO_TIPOS (ID);

ALTER TABLE MG.TBL_RECIBOS
	ADD FOREIGN KEY (ID_USER)
	REFERENCES MG.TBL_USERS (ID);


ALTER TABLE MG.TBL_TRANSFERENCIAS
	ADD FOREIGN KEY (ID_ENTIDAD)
	REFERENCES MG.TBL_ENTIDADES (ID);

ALTER TABLE MG.TBL_TRANSFERENCIAS
	ADD FOREIGN KEY (ID_EVENTO_TIPO)
	REFERENCES MG.TBL_EVENTO_TIPOS (ID);

ALTER TABLE MG.TBL_TRANSFERENCIAS
	ADD FOREIGN KEY (ID_USER)
	REFERENCES MG.TBL_USERS (ID);
