ALTER TABLE MG.TBL_TRANSFERENCIAS
	ADD COLUMN ID_EVENTO INTEGER;

ALTER TABLE MG.TBL_TRANSFERENCIAS
	ADD FOREIGN KEY (ID_EVENTO) REFERENCES MG.TBL_EVENTOS (ID);

ALTER TABLE MG.TBL_RECIBOS
	ADD COLUMN ID_EVENTO INTEGER;

ALTER TABLE MG.TBL_RECIBOS
	ADD FOREIGN KEY (ID_EVENTO) REFERENCES MG.TBL_EVENTOS (ID);