SELECT SUM(c.MONTO), SUM(c.atemp) FROM
(SELECT a.ID, a.MONTO, SUM(att.MONTO) as atemp FROM
MG.TBL_ASIENTOS a, MG.TBL_ASIENTOS_ASIENTOS_TEMPORALES aat, MG.TBL_ASIENTOS_TEMPORALES att
where aat.ID_ASIENTO = a.ID AND aat.ID_ASIENTO_TEMPORAL = att.ID
group by a.ID, a.MONTO) c
where c.MONTO <> c.atemp

SELECT f.NRO, f.RAZON_SOCIAL, f.IMPORTE_DONACION+f.IMPORTE_APORTE, c.ID, c.asientos
FROM
MG.TBL_FACTURAS f,
MG.TBL_FACTURAS_ASIENTOS fa,
(SELECT a.ID, a.MONTO as asientos, att.MONTO as atemp FROM
MG.TBL_ASIENTOS a, MG.TBL_ASIENTOS_ASIENTOS_TEMPORALES aat, MG.TBL_ASIENTOS_TEMPORALES att
where aat.ID_ASIENTO = a.ID AND aat.ID_ASIENTO_TEMPORAL = att.ID) c
WHERE f.NRO = fa.NRO_FACTURA
AND c.ID = fa.ID_ASIENTO
AND f.ANULADO = false