

CREATE TABLE MG.TBL_CATEGORIAS_TRIBUTARIAS (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	DESCRIPCION VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_COLECTAS (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	FECHA TIMESTAMP NOT NULL,
	DESCRIPCION VARCHAR(100),
	ID_CATEGORIA_TRIBUTARIA INTEGER NOT NULL,
	ID_USER INTEGER DEFAULT 0 NOT NULL,
	ID_GRUPO INTEGER DEFAULT 0 NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_COLECTAS_DETALLE (
	ID INTEGER NOT NULL,
	ID_COLECTA INTEGER NOT NULL,
	ID_MIEMBRO INTEGER NOT NULL,
	MONTO INTEGER NOT NULL,
	ID_USER INTEGER NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_GRUPOS (
	ID INTEGER NOT NULL,
	DESCRIPCION VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_GRUPOS_USERS (
	ID_USER INTEGER NOT NULL,
	ID_GRUPO INTEGER DEFAULT 0 NOT NULL,
	PRIMARY KEY (ID_GRUPO,ID_USER)
);

CREATE TABLE MG.TBL_IGLESIA (
	ID INTEGER NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	RUC INTEGER,
	CTACTE INTEGER,
	DOMICILIO VARCHAR(50),
	BOX INTEGER,
	PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_MIEMBROS (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	CTACTE INTEGER,
	DOMICILIO VARCHAR(50),
	BOX INTEGER,
	ID_USER INTEGER,
	PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_RECIBOS (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	FECHAHORA TIMESTAMP NOT NULL,
	CONCEPTO VARCHAR(50),
	MONTO INTEGER NOT NULL,
	ID_MIEMBRO INTEGER NOT NULL,
	ID_REMATE INTEGER NOT NULL,
	ID_USER INTEGER DEFAULT 0 NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_REMATES (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	FECHA TIMESTAMP NOT NULL,
	DESCRIPCION VARCHAR(100),
	"id_role" INTEGER,
	"id_user" INTEGER,
	PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_REMATES_CATEGORIAS (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	DESCRIPCION VARCHAR(50),
	PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_REMATES_CUOTAS (
	ID_REMATE INTEGER NOT NULL,
	FECHA_1 TIMESTAMP,
	FECHA_2 TIMESTAMP,
	FECHA_3 TIMESTAMP,
	FECHA_4 TIMESTAMP,
	ID_USER INTEGER,
	PRIMARY KEY (ID_REMATE)
);

CREATE TABLE MG.TBL_REMATES_DETALLE (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	FECHAHORA TIMESTAMP NOT NULL,
	OBSERVACION VARCHAR(50),
	MONTO INTEGER NOT NULL,
	ID_MIEMBRO INTEGER NOT NULL,
	ID_REMATE INTEGER NOT NULL,
	ID_CATEGORIA INTEGER NOT NULL,
	ID_USER INTEGER,
	PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_ROLES (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	DESCRIPCION VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_ROLES_USERS (
	ID_ROLE INTEGER NOT NULL,
	ID_USER INTEGER NOT NULL,
	PRIMARY KEY (ID_ROLE,ID_USER)
);

CREATE TABLE MG.TBL_TRANSFERENCIAS (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	FECHAHORA TIMESTAMP NOT NULL,
	CONCEPTO VARCHAR(50),
	MONTO INTEGER NOT NULL,
	ID_MIEMBRO INTEGER NOT NULL,
	ID_REMATE INTEGER NOT NULL,
	ID_USER INTEGER DEFAULT 0 NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE MG.TBL_USERS (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE MG.TBL_COLECTAS
	ADD FOREIGN KEY (ID_CATEGORIA_TRIBUTARIA)
	REFERENCES MG.TBL_CATEGORIAS_TRIBUTARIAS (ID);

ALTER TABLE MG.TBL_COLECTAS
	ADD FOREIGN KEY (ID_GRUPO)
	REFERENCES MG.TBL_GRUPOS (ID);

ALTER TABLE MG.TBL_COLECTAS
	ADD FOREIGN KEY (ID_USER)
	REFERENCES MG.TBL_USERS (ID);



ALTER TABLE MG.TBL_COLECTAS_DETALLE
	ADD FOREIGN KEY (ID_COLECTA)
	REFERENCES MG.TBL_COLECTAS (ID);

ALTER TABLE MG.TBL_COLECTAS_DETALLE
	ADD FOREIGN KEY (ID_MIEMBRO)
	REFERENCES MG.TBL_MIEMBROS (ID);

ALTER TABLE MG.TBL_COLECTAS_DETALLE
	ADD FOREIGN KEY (ID_USER)
	REFERENCES MG.TBL_USERS (ID);



ALTER TABLE MG.TBL_GRUPOS_USERS
	ADD FOREIGN KEY (ID_GRUPO)
	REFERENCES MG.TBL_GRUPOS (ID);

ALTER TABLE MG.TBL_GRUPOS_USERS
	ADD FOREIGN KEY (ID_USER)
	REFERENCES MG.TBL_USERS (ID);



ALTER TABLE MG.TBL_MIEMBROS
	ADD FOREIGN KEY (ID_USER)
	REFERENCES MG.TBL_USERS (ID);



ALTER TABLE MG.TBL_RECIBOS
	ADD FOREIGN KEY (ID_MIEMBRO)
	REFERENCES MG.TBL_MIEMBROS (ID);

ALTER TABLE MG.TBL_RECIBOS
	ADD FOREIGN KEY (ID_REMATE)
	REFERENCES MG.TBL_REMATES (ID);

ALTER TABLE MG.TBL_RECIBOS
	ADD FOREIGN KEY (ID_USER)
	REFERENCES MG.TBL_USERS (ID);



ALTER TABLE MG.TBL_REMATES_CUOTAS
	ADD FOREIGN KEY (ID_REMATE)
	REFERENCES MG.TBL_REMATES (ID);



ALTER TABLE MG.TBL_REMATES_DETALLE
	ADD FOREIGN KEY (ID_MIEMBRO)
	REFERENCES MG.TBL_MIEMBROS (ID);

ALTER TABLE MG.TBL_REMATES_DETALLE
	ADD FOREIGN KEY (ID_REMATE)
	REFERENCES MG.TBL_REMATES (ID);

ALTER TABLE MG.TBL_REMATES_DETALLE
	ADD FOREIGN KEY (ID_CATEGORIA)
	REFERENCES MG.TBL_REMATES_CATEGORIAS (ID);



ALTER TABLE MG.TBL_ROLES_USERS
	ADD FOREIGN KEY (ID_ROLE)
	REFERENCES MG.TBL_ROLES (ID);

ALTER TABLE MG.TBL_ROLES_USERS
	ADD FOREIGN KEY (ID_USER)
	REFERENCES MG.TBL_USERS (ID);



ALTER TABLE MG.TBL_TRANSFERENCIAS
	ADD FOREIGN KEY (ID_MIEMBRO)
	REFERENCES MG.TBL_MIEMBROS (ID);

ALTER TABLE MG.TBL_TRANSFERENCIAS
	ADD FOREIGN KEY (ID_REMATE)
	REFERENCES MG.TBL_REMATES (ID);

ALTER TABLE MG.TBL_TRANSFERENCIAS
	ADD FOREIGN KEY (ID_USER)
	REFERENCES MG.TBL_USERS (ID);



CREATE VIEW MG.RECIBO AS SELECT p.id, p.fechahora, d.nombre, p.concepto, p.monto FROM tbl_RECIBOS p, tbl_miembros d WHERE ((p.id_miembro = d.id));

CREATE VIEW MG.TRANSFERENCIA AS SELECT p.id, p.fechahora, d.nombre, p.concepto, p.monto FROM tbl_TRANSFERENCIAS p, tbl_miembros d WHERE ((p.id_miembro = d.id));

 p, tbl_miembros d WHERE ((p.id_miembro = d.id));
